apiVersion: integration/v1
kind: Trigger
name: jira-trigger-issue-deleted
version: 1
summary: Jira issue deleted
description: |
  This trigger fires when a Jira issue is deleted.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/jira-trigger-issue-deleted


examples:
- summary: When a Jira ticket is created
  content:
    apiVersion: v1
    kind: Trigger
    name: jira-issue-deleted
    source:
      type: webhook
      image: relaysh/jira-trigger-issue-deleted:latest
    binding:
      parameters:
        key: !Data key
        type: !Data type
        project: !Data project
        priority: !Data priority
        summary: !Data summary
        description: !Data description
