apiVersion: integration/v1
kind: Step
name: issue-create
version: 1
summary:
  Create a Jira issue
description: |
  Creates a new Jira issue.
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/jira-step-issue-create
schema: 
  spec: 
    source: file
    file: spec.schema.json
  outputs: 
    source: file
    file: outputs.schema.json
