apiVersion: integration/v1
kind: Step
name: issue-create
version: 1
summary:
  Create a Jira issue
description: |
  Creates a new Jira issue.
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/jira-step-issue-create
schemas: 
  spec: 
    source: file
    file: spec.schema.json
  outputs: 
    source: file
    file: outputs.schema.json
examples:
- summary: Create an issue
  content:
    apiVersion: v1
    kind: Step
    name: create-jira-issue
    image: relaysh/jira-step-issue-create
    spec:
      connection: !Connection { type: jira, name: jira-bot }
      issue:
        fields:
          project:
            key: !Parameter jiraProjectKey
          type:
            name: Task
          summary: !Parameter issueTitle
          description: !Fn.convertMarkdown [jira, !Parameter issueBody]