apiVersion: integration/v1
kind: Step
name: issue-transition
version: 4
summary:
  Transition a Jira issue
description: |
  Transitions a Jira issue to a specified status.
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/jira-step-issue-transition
schemas:
  spec:
    source: file
    file: spec.schema.json
examples:
- summary: Transition an issue
  content:
    apiVersion: v1
    kind: Step
    name: transition-jira-issue
    image: relaysh/jira-step-issue-transition
    spec:
      connection: !Connection { type: jira, name: jira-bot }
      issue:
        key: !Parameter jiraIssueKey
        fields:
          status:
            name: Resolved # Update with your Status
          resolution:
            name: Fixed # UPdate with your Resolution