apiVersion: integration/v1
kind: Trigger
name: jira-trigger-issue-created
version: 1
summary: Jira issue created
description: |
  This trigger fires when a Jira issue is created.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#
  event:
    source: file
    file: event.schema.json

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/jira-trigger-issue-created

examples:
- summary: When a Jira ticket is created
  content:
    apiVersion: v1
    kind: Trigger
    name: jira-issue-created
    source:
      type: webhook
      image: relaysh/jira-trigger-issue-created
    binding:
      parameters:
        key: !Data key
        type: !Data type
        project: !Data project
        priority: !Data priority
        summary: !Data summary
        description: !Data description
